runtime: python27
api_version: 1
threadsafe: true

handlers:
  - url: /
    static_files: index.html
    upload: index.html

  - url: /styles
    static_dir: styles

  - url: /img
    static_dir: /img

  - url: /(.*\.(html|css))
    static_files: \1
    upload: .*/
